### Modify
POST http://localhost:3000/points/1/modify HTTP/1.1
Content-Type: application/json

{
    "amount": 5,
    "reason": "completed homework",
    "set": false
}

### Points
GET http://localhost:3000/points/1 HTTP/1.1

### History
GET http://localhost:3000/points/3/history HTTP/1.1

### New Student
POST http://localhost:3000/students/new HTTP/1.1
Content-Type: application/json

{
    "name": "alice"
}

### Student List
GET http://localhost:3000/students/list HTTP/1.1
Content-Type: application/json
