CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    role INTEGER NOT NULL DEFAULT 0,
    password TEXT NOT NULL
)